baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'JunHitec'

google_analytics_id: "G-XDNMHVTC07"
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo.png"
  desktop: "images/logo/logo.png"
  desktop_height: "36px"
footer:
  copyright_text: 'Copyright ⓒ 2021, JunHitec'

seo:
  meta_og_title: "JunHitec"
  meta_og_type: "website"
  meta_og_url: "https://junhitec.com"
  meta_og_image: ""
  meta_og_description: "JunHitec"
  meta_twitter_card: ""
  meta_twitter_site: ""
  meta_twitter_creator: ""

collections:
  services:
    output: true
  team:
    output: false

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
